// Generated by CoffeeScript 1.6.3
(function() {
  var restore_options, save_options;

  save_options = function() {
    var ruby_version, select, status;
    select = document.getElementById('ruby-version');
    ruby_version = select.children[select.selectedIndex].value;
    localStorage['ruby_version'] = ruby_version;
    status = document.getElementById('status');
    status.innerHTML = 'Options Saved.';
    return setTimeout(function() {
      return status.innerHTML = "";
    }, 750);
  };

  restore_options = function() {
    var child, ruby_version, select, _i, _len, _ref, _results;
    ruby_version = localStorage['ruby_version'];
    if (!ruby_version) {
      return;
    }
    select = document.getElementById('ruby-version');
    _ref = select.children;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      child = _ref[_i];
      if (child.value === ruby_version) {
        child.selected = 'true';
        break;
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  document.addEventListener('DOMContentLoaded', restore_options);

  document.querySelector('#save').addEventListener('click', save_options);

}).call(this);
